spring:
  datasource:
    url: jdbc:h2:~/api-optimization
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true # @note: discussion ANTI-PATTERN
#    show-sql: true # replace with logging.level.org.hibernate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # db마다 max-size 다름

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate:type: trace